name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip aidl
          python3 -m pip install --upgrade pip
          python3 -m pip install \
            "buildozer==1.5.0" \
            "cython==3.0.2" \
            "python-for-android==2024.1.21"

      - name: Clean Buildozer state
        run: rm -rf .buildozer bin

      - name: Build APK
        run: yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: wifikiller-apk
          path: bin/*.apk
